// Граничные значения и базовые некорректные значения для проверки валидации
export const boundaryAndInvalidOrderIdVariations = [
  // Граничные значения для orderId (должен быть > 0 и <= 2147483647)
  { value: 0, description: "Ноль (граничное значение, должно быть > 0)" },
  { value: -1, description: "Отрицательное число -1 (граничное значение, должно быть > 0)" },
  { value: -2147483648, description: "Минимальное 32-битное signed integer (-2147483648)" },
  { value: -1000000, description: "Большое отрицательное число (-1000000)" },
  { value: 2147483648, description: "Число больше максимального 32-битного integer (2147483648)" },
  { value: 2147483649, description: "Число больше максимального 32-битного integer (2147483649)" },
  { value: 4294967295, description: "Максимальное 32-битное unsigned integer (4294967295)" },

  // Базовые некорректные значения
  { value: -100, description: "Отрицательное число (-100)" },
  { value: 0.5, description: "Дробное число (0.5)" },
  { value: 1.5, description: "Дробное число (1.5)" },
  { value: -0.1, description: "Отрицательное дробное число (-0.1)" },
  { value: Number.MAX_SAFE_INTEGER + 1, description: "Число больше MAX_SAFE_INTEGER" },
  { value: "9".repeat(100), description: "Очень длинное число (100 цифр)" },
  { value: "0", description: 'Строка "0"' },
  { value: "-1", description: 'Строка "-1"' },
  { value: "-2147483648", description: 'Строка "-2147483648" (минимальное 32-битное)' },
  { value: "2147483647", description: 'Строка "2147483647" (максимальное 32-битное)' },
  { value: "2147483648", description: 'Строка "2147483648" (больше максимального)' },
  { value: "1" + "A".repeat(1000), description: "Очень длинная строка (1000 символов)" },
  { value: "abc", description: 'Строка "abc"' },
  { value: "1.5", description: 'Строка "1.5"' },
  { value: null, description: "null" },
  { value: undefined, description: "undefined" },

  // Специальные символы
  { value: "1@", description: "Символ @" },
  { value: "1#", description: "Символ #" },
  { value: "1$", description: "Символ $" },
  { value: "1%", description: "Символ %" },
  { value: "1&", description: "Символ &" },
  { value: "1*", description: "Символ *" },
  { value: "1+", description: "Символ +" },
  { value: "1=", description: "Символ =" },
  { value: "1?", description: "Символ ?" },
  { value: "1!", description: "Символ !" },
  { value: "1~", description: "Символ ~" },
  { value: "1^", description: "Символ ^" },
  { value: "1|", description: "Символ |" },
  { value: "1\\", description: "Символ обратного слэша" },
  { value: "1/", description: "Символ слэша" },
  { value: "1<", description: "Символ <" },
  { value: "1>", description: "Символ >" },
  { value: "1[", description: "Символ [" },
  { value: "1]", description: "Символ ]" },
  { value: "1{", description: "Символ {" },
  { value: "1}", description: "Символ }" },
  { value: "1(", description: "Символ (" },
  { value: "1)", description: "Символ )" },
  { value: "1,", description: "Символ запятой" },
  { value: "1.", description: "Символ точки" },
  { value: "1;", description: "Символ точки с запятой" },
  { value: "1:", description: "Символ двоеточия" },
  { value: "1'", description: "Символ одинарной кавычки" },
  { value: '1"', description: "Символ двойной кавычки" },
  { value: "1`", description: "Символ обратной кавычки" },
  { value: "1 ", description: "Строка с пробелом в конце" },
  { value: " 1", description: "Строка с пробелом в начале" },
  { value: "1\t", description: "Строка с табуляцией" },
  { value: "1\n", description: "Строка с переводом строки" },
  { value: "1\r", description: "Строка с возвратом каретки" },
];

export const invalidOrderIdVariations = [...boundaryAndInvalidOrderIdVariations];
